/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 4.8.6
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCalendarWidget>
#include <QtGui/QCheckBox>
#include <QtGui/QComboBox>
#include <QtGui/QDateEdit>
#include <QtGui/QFrame>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QMainWindow>
#include <QtGui/QMenuBar>
#include <QtGui/QProgressBar>
#include <QtGui/QPushButton>
#include <QtGui/QSlider>
#include <QtGui/QTabWidget>
#include <QtGui/QTableWidget>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QTabWidget *tabWidget;
    QWidget *tab_home;
    QCalendarWidget *calendarWidget;
    QLabel *label_9;
    QGroupBox *groupBox_9;
    QLabel *label_10;
    QLabel *label_13;
    QLabel *label_14;
    QLineEdit *lineEdit_avghum;
    QLineEdit *lineEdit_avgtemp;
    QLineEdit *lineEdit_avglight;
    QLineEdit *smartDecMode;
    QLabel *label_16;
    QWidget *tab_roommgr;
    QLineEdit *roomEdit;
    QGroupBox *groupbox_dev1_3;
    QPushButton *pushbutton_set3;
    QLineEdit *device3ID;
    QLabel *dev1_id_4;
    QSlider *dev3_slider;
    QLabel *off_label_3;
    QFrame *line;
    QGroupBox *groupBox;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLineEdit *smartSwitchID;
    QLineEdit *smartSwitchTemp;
    QLineEdit *smartSwitchHum;
    QPushButton *pushbutton_setThreshold3_2;
    QLineEdit *smartSwitchLighting;
    QLineEdit *smartSwitchMotion;
    QGroupBox *groupbox_dev1_2;
    QLabel *dev1_name_2;
    QLabel *dev1_id_2;
    QSlider *dev2_slider;
    QLabel *off_label_2;
    QPushButton *pushbutton_set2;
    QLineEdit *device2Name;
    QLineEdit *device2ID;
    QLabel *dev1_name_3;
    QLabel *dev1_id_3;
    QCheckBox *checkBox_dev2;
    QGroupBox *groupbox_dev1;
    QLabel *dev1_name;
    QLabel *dev1_id;
    QSlider *dev1_slider;
    QLabel *off_label;
    QPushButton *pushbutton_set1;
    QLineEdit *device1Name;
    QLineEdit *device1ID;
    QCheckBox *checkBox_dev1;
    QLabel *label_room;
    QLabel *label_room_2;
    QComboBox *comboBox;
    QComboBox *comboBox_loadController;
    QWidget *tab_setupconfig;
    QGroupBox *groupBox_2;
    QComboBox *comboBox_selectRoom1;
    QPushButton *pushButton_4;
    QProgressBar *progressBar;
    QPushButton *pushButton_addDevice;
    QLabel *label_12;
    QPushButton *pushButton_addDevice_2;
    QTableWidget *tableWidget_3;
    QGroupBox *groupBox_3;
    QLabel *label_7;
    QComboBox *comboBox_selectRoom2;
    QTableWidget *tableWidget_2;
    QPushButton *pushButton_7;
    QGroupBox *groupBox_4;
    QCheckBox *checkBox_smartDM;
    QLabel *label_8;
    QGroupBox *groupBox_5;
    QLineEdit *textBox_newRoom;
    QPushButton *button_NewRoom;
    QGroupBox *groupBox_6;
    QPushButton *button_deleteRoom;
    QComboBox *comboBox_deleteroomlist;
    QDateEdit *dateEdit;
    QLabel *label_15;
    QWidget *tab_help;
    QGroupBox *groupBox_7;
    QLabel *dev1_id_5;
    QLabel *dev1_id_6;
    QLabel *dev1_id_7;
    QLabel *dev1_id_14;
    QLabel *dev1_id_15;
    QLabel *dev1_id_16;
    QLabel *dev1_id_17;
    QLabel *dev1_id_18;
    QLabel *dev1_id_19;
    QGroupBox *groupBox_8;
    QLabel *dev1_id_8;
    QLabel *dev1_id_9;
    QLabel *dev1_id_10;
    QLabel *dev1_id_11;
    QLabel *dev1_id_12;
    QLabel *dev1_id_13;
    QCheckBox *checkBox;
    QCheckBox *checkBox_3;
    QCheckBox *checkBox_4;
    QCheckBox *checkBox_2;
    QLabel *label;
    QLabel *label_11;
    QLabel *label_6;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QMenuBar *menuBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(800, 515);
        MainWindow->setStyleSheet(QString::fromUtf8("#MainWindow{\n"
"background: rgb(63, 13, 14);\n"
"}\n"
"\n"
"#tabWidget{s\n"
"background: rgb(63, 13, 14);\n"
"}"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(10, 80, 781, 361));
        tabWidget->setStyleSheet(QString::fromUtf8("#tabWidget{\n"
"background: rgb(164, 137, 0)\n"
"}"));
        tab_home = new QWidget();
        tab_home->setObjectName(QString::fromUtf8("tab_home"));
        calendarWidget = new QCalendarWidget(tab_home);
        calendarWidget->setObjectName(QString::fromUtf8("calendarWidget"));
        calendarWidget->setEnabled(false);
        calendarWidget->setGeometry(QRect(310, 80, 451, 172));
        calendarWidget->setGridVisible(true);
        calendarWidget->setDateEditEnabled(false);
        calendarWidget->setDateEditAcceptDelay(1500);
        label_9 = new QLabel(tab_home);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(0, 20, 781, 41));
        QFont font;
        font.setPointSize(12);
        label_9->setFont(font);
        label_9->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        label_9->setAlignment(Qt::AlignCenter);
        groupBox_9 = new QGroupBox(tab_home);
        groupBox_9->setObjectName(QString::fromUtf8("groupBox_9"));
        groupBox_9->setGeometry(QRect(10, 90, 281, 151));
        label_10 = new QLabel(groupBox_9);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(10, 30, 141, 20));
        label_13 = new QLabel(groupBox_9);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(10, 70, 141, 20));
        label_14 = new QLabel(groupBox_9);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(10, 110, 141, 20));
        lineEdit_avghum = new QLineEdit(groupBox_9);
        lineEdit_avghum->setObjectName(QString::fromUtf8("lineEdit_avghum"));
        lineEdit_avghum->setGeometry(QRect(150, 70, 113, 27));
        lineEdit_avghum->setReadOnly(true);
        lineEdit_avgtemp = new QLineEdit(groupBox_9);
        lineEdit_avgtemp->setObjectName(QString::fromUtf8("lineEdit_avgtemp"));
        lineEdit_avgtemp->setGeometry(QRect(150, 30, 113, 27));
        lineEdit_avgtemp->setReadOnly(true);
        lineEdit_avglight = new QLineEdit(groupBox_9);
        lineEdit_avglight->setObjectName(QString::fromUtf8("lineEdit_avglight"));
        lineEdit_avglight->setGeometry(QRect(150, 110, 113, 27));
        lineEdit_avglight->setReadOnly(true);
        smartDecMode = new QLineEdit(tab_home);
        smartDecMode->setObjectName(QString::fromUtf8("smartDecMode"));
        smartDecMode->setGeometry(QRect(160, 270, 81, 27));
        smartDecMode->setReadOnly(true);
        label_16 = new QLabel(tab_home);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(10, 270, 151, 17));
        tabWidget->addTab(tab_home, QString());
        tab_roommgr = new QWidget();
        tab_roommgr->setObjectName(QString::fromUtf8("tab_roommgr"));
        roomEdit = new QLineEdit(tab_roommgr);
        roomEdit->setObjectName(QString::fromUtf8("roomEdit"));
        roomEdit->setGeometry(QRect(280, 10, 221, 31));
        QFont font1;
        font1.setPointSize(16);
        roomEdit->setFont(font1);
        roomEdit->setReadOnly(true);
        groupbox_dev1_3 = new QGroupBox(tab_roommgr);
        groupbox_dev1_3->setObjectName(QString::fromUtf8("groupbox_dev1_3"));
        groupbox_dev1_3->setGeometry(QRect(380, 130, 171, 181));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QBrush brush1(QColor(159, 158, 158, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        groupbox_dev1_3->setPalette(palette);
        pushbutton_set3 = new QPushButton(groupbox_dev1_3);
        pushbutton_set3->setObjectName(QString::fromUtf8("pushbutton_set3"));
        pushbutton_set3->setGeometry(QRect(40, 150, 111, 27));
        device3ID = new QLineEdit(groupbox_dev1_3);
        device3ID->setObjectName(QString::fromUtf8("device3ID"));
        device3ID->setGeometry(QRect(60, 20, 101, 27));
        device3ID->setReadOnly(true);
        dev1_id_4 = new QLabel(groupbox_dev1_3);
        dev1_id_4->setObjectName(QString::fromUtf8("dev1_id_4"));
        dev1_id_4->setGeometry(QRect(10, 30, 41, 17));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        dev1_id_4->setPalette(palette1);
        dev3_slider = new QSlider(groupbox_dev1_3);
        dev3_slider->setObjectName(QString::fromUtf8("dev3_slider"));
        dev3_slider->setGeometry(QRect(20, 100, 141, 29));
        dev3_slider->setMaximum(1);
        dev3_slider->setPageStep(4);
        dev3_slider->setOrientation(Qt::Horizontal);
        off_label_3 = new QLabel(groupbox_dev1_3);
        off_label_3->setObjectName(QString::fromUtf8("off_label_3"));
        off_label_3->setGeometry(QRect(20, 130, 151, 20));
        QPalette palette2;
        QBrush brush2(QColor(255, 255, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        off_label_3->setPalette(palette2);
        line = new QFrame(tab_roommgr);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(550, 50, 20, 281));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        groupBox = new QGroupBox(tab_roommgr);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(570, 50, 201, 251));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        groupBox->setPalette(palette3);
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(10, 40, 21, 17));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        label_2->setPalette(palette4);
        label_3 = new QLabel(groupBox);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(10, 70, 91, 17));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_3->setPalette(palette5);
        label_4 = new QLabel(groupBox);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(10, 100, 67, 17));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_4->setPalette(palette6);
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(10, 130, 67, 17));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_5->setPalette(palette7);
        smartSwitchID = new QLineEdit(groupBox);
        smartSwitchID->setObjectName(QString::fromUtf8("smartSwitchID"));
        smartSwitchID->setGeometry(QRect(100, 30, 71, 27));
        smartSwitchTemp = new QLineEdit(groupBox);
        smartSwitchTemp->setObjectName(QString::fromUtf8("smartSwitchTemp"));
        smartSwitchTemp->setGeometry(QRect(100, 60, 71, 27));
        smartSwitchHum = new QLineEdit(groupBox);
        smartSwitchHum->setObjectName(QString::fromUtf8("smartSwitchHum"));
        smartSwitchHum->setGeometry(QRect(100, 90, 71, 27));
        pushbutton_setThreshold3_2 = new QPushButton(groupBox);
        pushbutton_setThreshold3_2->setObjectName(QString::fromUtf8("pushbutton_setThreshold3_2"));
        pushbutton_setThreshold3_2->setGeometry(QRect(20, 160, 161, 27));
        smartSwitchLighting = new QLineEdit(groupBox);
        smartSwitchLighting->setObjectName(QString::fromUtf8("smartSwitchLighting"));
        smartSwitchLighting->setGeometry(QRect(100, 120, 71, 27));
        smartSwitchMotion = new QLineEdit(groupBox);
        smartSwitchMotion->setObjectName(QString::fromUtf8("smartSwitchMotion"));
        smartSwitchMotion->setGeometry(QRect(70, 200, 61, 27));
        groupbox_dev1_2 = new QGroupBox(tab_roommgr);
        groupbox_dev1_2->setObjectName(QString::fromUtf8("groupbox_dev1_2"));
        groupbox_dev1_2->setGeometry(QRect(200, 130, 171, 181));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        groupbox_dev1_2->setPalette(palette8);
        dev1_name_2 = new QLabel(groupbox_dev1_2);
        dev1_name_2->setObjectName(QString::fromUtf8("dev1_name_2"));
        dev1_name_2->setGeometry(QRect(10, 30, 41, 17));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        dev1_name_2->setPalette(palette9);
        dev1_id_2 = new QLabel(groupbox_dev1_2);
        dev1_id_2->setObjectName(QString::fromUtf8("dev1_id_2"));
        dev1_id_2->setGeometry(QRect(10, 60, 41, 17));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        dev1_id_2->setPalette(palette10);
        dev2_slider = new QSlider(groupbox_dev1_2);
        dev2_slider->setObjectName(QString::fromUtf8("dev2_slider"));
        dev2_slider->setGeometry(QRect(10, 100, 141, 29));
        dev2_slider->setMaximum(4);
        dev2_slider->setPageStep(4);
        dev2_slider->setOrientation(Qt::Horizontal);
        off_label_2 = new QLabel(groupbox_dev1_2);
        off_label_2->setObjectName(QString::fromUtf8("off_label_2"));
        off_label_2->setGeometry(QRect(10, 130, 151, 20));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        off_label_2->setPalette(palette11);
        pushbutton_set2 = new QPushButton(groupbox_dev1_2);
        pushbutton_set2->setObjectName(QString::fromUtf8("pushbutton_set2"));
        pushbutton_set2->setGeometry(QRect(30, 150, 111, 27));
        device2Name = new QLineEdit(groupbox_dev1_2);
        device2Name->setObjectName(QString::fromUtf8("device2Name"));
        device2Name->setGeometry(QRect(60, 20, 101, 27));
        device2ID = new QLineEdit(groupbox_dev1_2);
        device2ID->setObjectName(QString::fromUtf8("device2ID"));
        device2ID->setGeometry(QRect(60, 50, 101, 27));
        device2ID->setReadOnly(true);
        dev1_name_3 = new QLabel(groupbox_dev1_2);
        dev1_name_3->setObjectName(QString::fromUtf8("dev1_name_3"));
        dev1_name_3->setGeometry(QRect(190, 40, 41, 17));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        dev1_name_3->setPalette(palette12);
        dev1_id_3 = new QLabel(groupbox_dev1_2);
        dev1_id_3->setObjectName(QString::fromUtf8("dev1_id_3"));
        dev1_id_3->setGeometry(QRect(190, 60, 41, 17));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        dev1_id_3->setPalette(palette13);
        checkBox_dev2 = new QCheckBox(groupbox_dev1_2);
        checkBox_dev2->setObjectName(QString::fromUtf8("checkBox_dev2"));
        checkBox_dev2->setGeometry(QRect(10, 80, 121, 22));
        groupbox_dev1 = new QGroupBox(tab_roommgr);
        groupbox_dev1->setObjectName(QString::fromUtf8("groupbox_dev1"));
        groupbox_dev1->setGeometry(QRect(10, 130, 171, 181));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Active, QPalette::Text, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        groupbox_dev1->setPalette(palette14);
        dev1_name = new QLabel(groupbox_dev1);
        dev1_name->setObjectName(QString::fromUtf8("dev1_name"));
        dev1_name->setGeometry(QRect(10, 30, 41, 17));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        dev1_name->setPalette(palette15);
        dev1_id = new QLabel(groupbox_dev1);
        dev1_id->setObjectName(QString::fromUtf8("dev1_id"));
        dev1_id->setGeometry(QRect(10, 60, 41, 17));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette16.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette16.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette16.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        dev1_id->setPalette(palette16);
        dev1_slider = new QSlider(groupbox_dev1);
        dev1_slider->setObjectName(QString::fromUtf8("dev1_slider"));
        dev1_slider->setGeometry(QRect(10, 100, 141, 29));
        dev1_slider->setMaximum(4);
        dev1_slider->setPageStep(4);
        dev1_slider->setOrientation(Qt::Horizontal);
        off_label = new QLabel(groupbox_dev1);
        off_label->setObjectName(QString::fromUtf8("off_label"));
        off_label->setGeometry(QRect(10, 130, 151, 20));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette17.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette17.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        off_label->setPalette(palette17);
        pushbutton_set1 = new QPushButton(groupbox_dev1);
        pushbutton_set1->setObjectName(QString::fromUtf8("pushbutton_set1"));
        pushbutton_set1->setGeometry(QRect(30, 150, 111, 27));
        device1Name = new QLineEdit(groupbox_dev1);
        device1Name->setObjectName(QString::fromUtf8("device1Name"));
        device1Name->setGeometry(QRect(60, 20, 101, 27));
        device1ID = new QLineEdit(groupbox_dev1);
        device1ID->setObjectName(QString::fromUtf8("device1ID"));
        device1ID->setGeometry(QRect(60, 50, 101, 27));
        device1ID->setReadOnly(true);
        checkBox_dev1 = new QCheckBox(groupbox_dev1);
        checkBox_dev1->setObjectName(QString::fromUtf8("checkBox_dev1"));
        checkBox_dev1->setGeometry(QRect(10, 80, 121, 22));
        label_room = new QLabel(tab_roommgr);
        label_room->setObjectName(QString::fromUtf8("label_room"));
        label_room->setGeometry(QRect(80, 60, 91, 17));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette18.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette18.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        label_room->setPalette(palette18);
        label_room_2 = new QLabel(tab_roommgr);
        label_room_2->setObjectName(QString::fromUtf8("label_room_2"));
        label_room_2->setGeometry(QRect(80, 90, 161, 17));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette19.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette19.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette19.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette19.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        label_room_2->setPalette(palette19);
        comboBox = new QComboBox(tab_roommgr);
        comboBox->setObjectName(QString::fromUtf8("comboBox"));
        comboBox->setGeometry(QRect(250, 60, 191, 27));
        comboBox_loadController = new QComboBox(tab_roommgr);
        comboBox_loadController->setObjectName(QString::fromUtf8("comboBox_loadController"));
        comboBox_loadController->setGeometry(QRect(250, 90, 191, 27));
        tabWidget->addTab(tab_roommgr, QString());
        tab_setupconfig = new QWidget();
        tab_setupconfig->setObjectName(QString::fromUtf8("tab_setupconfig"));
        groupBox_2 = new QGroupBox(tab_setupconfig);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 10, 261, 281));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette20.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette20.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette20.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette20.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette20.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        groupBox_2->setPalette(palette20);
        comboBox_selectRoom1 = new QComboBox(groupBox_2);
        comboBox_selectRoom1->setObjectName(QString::fromUtf8("comboBox_selectRoom1"));
        comboBox_selectRoom1->setGeometry(QRect(100, 30, 151, 27));
        pushButton_4 = new QPushButton(groupBox_2);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(20, 60, 99, 31));
        progressBar = new QProgressBar(groupBox_2);
        progressBar->setObjectName(QString::fromUtf8("progressBar"));
        progressBar->setGeometry(QRect(130, 60, 118, 31));
        progressBar->setMaximum(60);
        progressBar->setValue(0);
        progressBar->setTextVisible(false);
        pushButton_addDevice = new QPushButton(groupBox_2);
        pushButton_addDevice->setObjectName(QString::fromUtf8("pushButton_addDevice"));
        pushButton_addDevice->setGeometry(QRect(50, 220, 151, 27));
        label_12 = new QLabel(groupBox_2);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(10, 30, 91, 17));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette21.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_12->setPalette(palette21);
        pushButton_addDevice_2 = new QPushButton(groupBox_2);
        pushButton_addDevice_2->setObjectName(QString::fromUtf8("pushButton_addDevice_2"));
        pushButton_addDevice_2->setGeometry(QRect(40, 250, 171, 27));
        tableWidget_3 = new QTableWidget(groupBox_2);
        if (tableWidget_3->columnCount() < 1)
            tableWidget_3->setColumnCount(1);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidget_3->setHorizontalHeaderItem(0, __qtablewidgetitem);
        tableWidget_3->setObjectName(QString::fromUtf8("tableWidget_3"));
        tableWidget_3->setGeometry(QRect(20, 100, 231, 111));
        tableWidget_3->setRowCount(0);
        tableWidget_3->horizontalHeader()->setDefaultSectionSize(200);
        groupBox_3 = new QGroupBox(tab_setupconfig);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(280, 10, 271, 281));
        QPalette palette22;
        palette22.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette22.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette22.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette22.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        groupBox_3->setPalette(palette22);
        label_7 = new QLabel(groupBox_3);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(10, 30, 91, 17));
        QPalette palette23;
        palette23.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette23.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_7->setPalette(palette23);
        comboBox_selectRoom2 = new QComboBox(groupBox_3);
        comboBox_selectRoom2->setObjectName(QString::fromUtf8("comboBox_selectRoom2"));
        comboBox_selectRoom2->setGeometry(QRect(100, 30, 151, 27));
        tableWidget_2 = new QTableWidget(groupBox_3);
        if (tableWidget_2->columnCount() < 1)
            tableWidget_2->setColumnCount(1);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidget_2->setHorizontalHeaderItem(0, __qtablewidgetitem1);
        if (tableWidget_2->rowCount() < 3)
            tableWidget_2->setRowCount(3);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidget_2->setVerticalHeaderItem(0, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidget_2->setVerticalHeaderItem(1, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidget_2->setVerticalHeaderItem(2, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        __qtablewidgetitem5->setFlags(Qt::ItemIsSelectable|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        tableWidget_2->setItem(0, 0, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidget_2->setItem(2, 0, __qtablewidgetitem6);
        tableWidget_2->setObjectName(QString::fromUtf8("tableWidget_2"));
        tableWidget_2->setGeometry(QRect(20, 100, 231, 111));
        tableWidget_2->horizontalHeader()->setDefaultSectionSize(200);
        pushButton_7 = new QPushButton(groupBox_3);
        pushButton_7->setObjectName(QString::fromUtf8("pushButton_7"));
        pushButton_7->setGeometry(QRect(50, 220, 171, 27));
        groupBox_4 = new QGroupBox(tab_setupconfig);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(560, 10, 191, 51));
        QPalette palette24;
        palette24.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette24.setBrush(QPalette::Active, QPalette::Text, brush2);
        QBrush brush3(QColor(6, 0, 0, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette24.setBrush(QPalette::Active, QPalette::BrightText, brush3);
        palette24.setBrush(QPalette::Active, QPalette::Base, brush);
        palette24.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette24.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette24.setBrush(QPalette::Inactive, QPalette::BrightText, brush3);
        palette24.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette24.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette24.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette24.setBrush(QPalette::Disabled, QPalette::BrightText, brush3);
        palette24.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        groupBox_4->setPalette(palette24);
        checkBox_smartDM = new QCheckBox(groupBox_4);
        checkBox_smartDM->setObjectName(QString::fromUtf8("checkBox_smartDM"));
        checkBox_smartDM->setGeometry(QRect(110, 20, 21, 22));
        label_8 = new QLabel(groupBox_4);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(50, 20, 61, 20));
        QPalette palette25;
        palette25.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette25.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette25.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette25.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette25.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        label_8->setPalette(palette25);
        groupBox_5 = new QGroupBox(tab_setupconfig);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(560, 70, 191, 81));
        QPalette palette26;
        palette26.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette26.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette26.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette26.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette26.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette26.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        groupBox_5->setPalette(palette26);
        textBox_newRoom = new QLineEdit(groupBox_5);
        textBox_newRoom->setObjectName(QString::fromUtf8("textBox_newRoom"));
        textBox_newRoom->setGeometry(QRect(10, 20, 161, 27));
        button_NewRoom = new QPushButton(groupBox_5);
        button_NewRoom->setObjectName(QString::fromUtf8("button_NewRoom"));
        button_NewRoom->setGeometry(QRect(40, 50, 99, 27));
        groupBox_6 = new QGroupBox(tab_setupconfig);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(560, 160, 191, 81));
        QPalette palette27;
        palette27.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette27.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette27.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette27.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette27.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette27.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        groupBox_6->setPalette(palette27);
        button_deleteRoom = new QPushButton(groupBox_6);
        button_deleteRoom->setObjectName(QString::fromUtf8("button_deleteRoom"));
        button_deleteRoom->setGeometry(QRect(40, 50, 99, 27));
        comboBox_deleteroomlist = new QComboBox(groupBox_6);
        comboBox_deleteroomlist->setObjectName(QString::fromUtf8("comboBox_deleteroomlist"));
        comboBox_deleteroomlist->setGeometry(QRect(10, 20, 151, 27));
        dateEdit = new QDateEdit(tab_setupconfig);
        dateEdit->setObjectName(QString::fromUtf8("dateEdit"));
        dateEdit->setGeometry(QRect(650, 260, 110, 27));
        label_15 = new QLabel(tab_setupconfig);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(580, 260, 91, 17));
        QPalette palette28;
        palette28.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette28.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette28.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_15->setPalette(palette28);
        tabWidget->addTab(tab_setupconfig, QString());
        tab_help = new QWidget();
        tab_help->setObjectName(QString::fromUtf8("tab_help"));
        groupBox_7 = new QGroupBox(tab_help);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(10, 30, 331, 261));
        QPalette palette29;
        palette29.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette29.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette29.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette29.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette29.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette29.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        groupBox_7->setPalette(palette29);
        groupBox_7->setStyleSheet(QString::fromUtf8("font: 11pt \"Ubuntu\";"));
        dev1_id_5 = new QLabel(groupBox_7);
        dev1_id_5->setObjectName(QString::fromUtf8("dev1_id_5"));
        dev1_id_5->setGeometry(QRect(10, 40, 341, 17));
        QPalette palette30;
        palette30.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette30.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette30.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette30.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette30.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette30.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        dev1_id_5->setPalette(palette30);
        dev1_id_6 = new QLabel(groupBox_7);
        dev1_id_6->setObjectName(QString::fromUtf8("dev1_id_6"));
        dev1_id_6->setGeometry(QRect(20, 60, 281, 17));
        QPalette palette31;
        palette31.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette31.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette31.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette31.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette31.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette31.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        dev1_id_6->setPalette(palette31);
        dev1_id_7 = new QLabel(groupBox_7);
        dev1_id_7->setObjectName(QString::fromUtf8("dev1_id_7"));
        dev1_id_7->setGeometry(QRect(10, 90, 301, 17));
        QPalette palette32;
        palette32.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette32.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette32.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette32.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette32.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette32.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        dev1_id_7->setPalette(palette32);
        dev1_id_14 = new QLabel(groupBox_7);
        dev1_id_14->setObjectName(QString::fromUtf8("dev1_id_14"));
        dev1_id_14->setGeometry(QRect(20, 110, 301, 17));
        QPalette palette33;
        palette33.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette33.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette33.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette33.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette33.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        dev1_id_14->setPalette(palette33);
        dev1_id_15 = new QLabel(groupBox_7);
        dev1_id_15->setObjectName(QString::fromUtf8("dev1_id_15"));
        dev1_id_15->setGeometry(QRect(10, 140, 311, 17));
        QPalette palette34;
        palette34.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette34.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette34.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette34.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette34.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette34.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        dev1_id_15->setPalette(palette34);
        dev1_id_16 = new QLabel(groupBox_7);
        dev1_id_16->setObjectName(QString::fromUtf8("dev1_id_16"));
        dev1_id_16->setGeometry(QRect(20, 160, 301, 17));
        QPalette palette35;
        palette35.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette35.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette35.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette35.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette35.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette35.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        dev1_id_16->setPalette(palette35);
        dev1_id_17 = new QLabel(groupBox_7);
        dev1_id_17->setObjectName(QString::fromUtf8("dev1_id_17"));
        dev1_id_17->setGeometry(QRect(10, 190, 311, 17));
        QPalette palette36;
        palette36.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette36.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette36.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette36.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette36.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette36.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        dev1_id_17->setPalette(palette36);
        dev1_id_18 = new QLabel(groupBox_7);
        dev1_id_18->setObjectName(QString::fromUtf8("dev1_id_18"));
        dev1_id_18->setGeometry(QRect(10, 220, 321, 17));
        QPalette palette37;
        palette37.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette37.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette37.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette37.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette37.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette37.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        dev1_id_18->setPalette(palette37);
        dev1_id_19 = new QLabel(groupBox_7);
        dev1_id_19->setObjectName(QString::fromUtf8("dev1_id_19"));
        dev1_id_19->setGeometry(QRect(20, 240, 221, 17));
        QPalette palette38;
        palette38.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette38.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette38.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette38.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette38.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette38.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        dev1_id_19->setPalette(palette38);
        groupBox_8 = new QGroupBox(tab_help);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(360, 30, 401, 261));
        QPalette palette39;
        palette39.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette39.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette39.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette39.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette39.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette39.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette39.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette39.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette39.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        groupBox_8->setPalette(palette39);
        groupBox_8->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"font: 11pt \"Ubuntu\";"));
        dev1_id_8 = new QLabel(groupBox_8);
        dev1_id_8->setObjectName(QString::fromUtf8("dev1_id_8"));
        dev1_id_8->setGeometry(QRect(20, 40, 461, 17));
        QPalette palette40;
        palette40.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette40.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette40.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette40.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette40.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette40.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette40.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette40.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette40.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        dev1_id_8->setPalette(palette40);
        dev1_id_9 = new QLabel(groupBox_8);
        dev1_id_9->setObjectName(QString::fromUtf8("dev1_id_9"));
        dev1_id_9->setGeometry(QRect(30, 80, 461, 17));
        QPalette palette41;
        palette41.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette41.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette41.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette41.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette41.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette41.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette41.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette41.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette41.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        dev1_id_9->setPalette(palette41);
        dev1_id_10 = new QLabel(groupBox_8);
        dev1_id_10->setObjectName(QString::fromUtf8("dev1_id_10"));
        dev1_id_10->setGeometry(QRect(20, 100, 461, 17));
        QPalette palette42;
        palette42.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette42.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette42.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette42.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette42.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette42.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette42.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette42.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette42.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        dev1_id_10->setPalette(palette42);
        dev1_id_11 = new QLabel(groupBox_8);
        dev1_id_11->setObjectName(QString::fromUtf8("dev1_id_11"));
        dev1_id_11->setGeometry(QRect(30, 140, 461, 17));
        QPalette palette43;
        palette43.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette43.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette43.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette43.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette43.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette43.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette43.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette43.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette43.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        dev1_id_11->setPalette(palette43);
        dev1_id_12 = new QLabel(groupBox_8);
        dev1_id_12->setObjectName(QString::fromUtf8("dev1_id_12"));
        dev1_id_12->setGeometry(QRect(30, 60, 461, 17));
        QPalette palette44;
        palette44.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette44.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette44.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette44.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette44.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette44.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette44.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette44.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette44.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        dev1_id_12->setPalette(palette44);
        dev1_id_13 = new QLabel(groupBox_8);
        dev1_id_13->setObjectName(QString::fromUtf8("dev1_id_13"));
        dev1_id_13->setGeometry(QRect(30, 120, 461, 17));
        QPalette palette45;
        palette45.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette45.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette45.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette45.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette45.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette45.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette45.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette45.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette45.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        dev1_id_13->setPalette(palette45);
        checkBox = new QCheckBox(tab_help);
        checkBox->setObjectName(QString::fromUtf8("checkBox"));
        checkBox->setGeometry(QRect(250, 0, 98, 22));
        checkBox_3 = new QCheckBox(tab_help);
        checkBox_3->setObjectName(QString::fromUtf8("checkBox_3"));
        checkBox_3->setGeometry(QRect(590, 0, 98, 22));
        checkBox_4 = new QCheckBox(tab_help);
        checkBox_4->setObjectName(QString::fromUtf8("checkBox_4"));
        checkBox_4->setGeometry(QRect(360, 0, 98, 22));
        checkBox_2 = new QCheckBox(tab_help);
        checkBox_2->setObjectName(QString::fromUtf8("checkBox_2"));
        checkBox_2->setGeometry(QRect(470, 0, 98, 22));
        tabWidget->addTab(tab_help, QString());
        label = new QLabel(centralWidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(310, 10, 191, 51));
        label->setStyleSheet(QString::fromUtf8("font: 11pt \"Ubuntu Condensed\";"));
        label_11 = new QLabel(centralWidget);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(630, 440, 161, 20));
        QPalette palette46;
        palette46.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette46.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette46.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        label_11->setPalette(palette46);
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(0, -330, 771, 851));
        label_6->setPixmap(QPixmap(QString::fromUtf8("jarvishead3.jpg")));
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(600, 20, 181, 61));
        pushButton_2 = new QPushButton(centralWidget);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(20, 450, 99, 27));
        MainWindow->setCentralWidget(centralWidget);
        label_6->raise();
        label->raise();
        label_11->raise();
        tabWidget->raise();
        pushButton->raise();
        pushButton_2->raise();
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 800, 25));
        MainWindow->setMenuBar(menuBar);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(2);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("MainWindow", "Welcome to your Gesture-controlled Automated Residency Via Intelligent System (GARVIS)!", 0, QApplication::UnicodeUTF8));
        groupBox_9->setTitle(QApplication::translate("MainWindow", "Average Home Statistics", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("MainWindow", "Home Temperature", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("MainWindow", "Home Humidity", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("MainWindow", "Home Lighting", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("MainWindow", "Smart Decision Mode", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_home), QApplication::translate("MainWindow", "Home", 0, QApplication::UnicodeUTF8));
        roomEdit->setText(QApplication::translate("MainWindow", "Current Room", 0, QApplication::UnicodeUTF8));
        groupbox_dev1_3->setTitle(QApplication::translate("MainWindow", "Vent", 0, QApplication::UnicodeUTF8));
        pushbutton_set3->setText(QApplication::translate("MainWindow", "Set", 0, QApplication::UnicodeUTF8));
        dev1_id_4->setText(QApplication::translate("MainWindow", "ID", 0, QApplication::UnicodeUTF8));
        off_label_3->setText(QApplication::translate("MainWindow", "Off                           On", 0, QApplication::UnicodeUTF8));
        groupBox->setTitle(QApplication::translate("MainWindow", "Smart Switch", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("MainWindow", "ID", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("MainWindow", "Temperature", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("MainWindow", "Humidity", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("MainWindow", "Lighting", 0, QApplication::UnicodeUTF8));
        pushbutton_setThreshold3_2->setText(QApplication::translate("MainWindow", "Set Room Thresholds", 0, QApplication::UnicodeUTF8));
        smartSwitchMotion->setText(QApplication::translate("MainWindow", "Motion", 0, QApplication::UnicodeUTF8));
        groupbox_dev1_2->setTitle(QApplication::translate("MainWindow", "Device 2", 0, QApplication::UnicodeUTF8));
        dev1_name_2->setText(QApplication::translate("MainWindow", "Name", 0, QApplication::UnicodeUTF8));
        dev1_id_2->setText(QApplication::translate("MainWindow", "ID", 0, QApplication::UnicodeUTF8));
        off_label_2->setText(QApplication::translate("MainWindow", "Off                           On", 0, QApplication::UnicodeUTF8));
        pushbutton_set2->setText(QApplication::translate("MainWindow", "Set", 0, QApplication::UnicodeUTF8));
        dev1_name_3->setText(QApplication::translate("MainWindow", "Name", 0, QApplication::UnicodeUTF8));
        dev1_id_3->setText(QApplication::translate("MainWindow", "ID", 0, QApplication::UnicodeUTF8));
        checkBox_dev2->setText(QApplication::translate("MainWindow", "Incremental", 0, QApplication::UnicodeUTF8));
        groupbox_dev1->setTitle(QApplication::translate("MainWindow", "Device 1", 0, QApplication::UnicodeUTF8));
        dev1_name->setText(QApplication::translate("MainWindow", "Name", 0, QApplication::UnicodeUTF8));
        dev1_id->setText(QApplication::translate("MainWindow", "ID", 0, QApplication::UnicodeUTF8));
        off_label->setText(QApplication::translate("MainWindow", "Off                           On", 0, QApplication::UnicodeUTF8));
        pushbutton_set1->setText(QApplication::translate("MainWindow", "Set", 0, QApplication::UnicodeUTF8));
        checkBox_dev1->setText(QApplication::translate("MainWindow", "Incremental", 0, QApplication::UnicodeUTF8));
        label_room->setText(QApplication::translate("MainWindow", "Select Room", 0, QApplication::UnicodeUTF8));
        label_room_2->setText(QApplication::translate("MainWindow", "Select Load Controller", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_roommgr), QApplication::translate("MainWindow", "Room Manager", 0, QApplication::UnicodeUTF8));
        groupBox_2->setTitle(QApplication::translate("MainWindow", "Add Devices", 0, QApplication::UnicodeUTF8));
        pushButton_4->setText(QApplication::translate("MainWindow", "Detect", 0, QApplication::UnicodeUTF8));
        pushButton_addDevice->setText(QApplication::translate("MainWindow", "Add Selected Device", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("MainWindow", "Select Room", 0, QApplication::UnicodeUTF8));
        pushButton_addDevice_2->setText(QApplication::translate("MainWindow", "Launch Device Startup", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem = tableWidget_3->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("MainWindow", "Devices", 0, QApplication::UnicodeUTF8));
        groupBox_3->setTitle(QApplication::translate("MainWindow", "Delete Device", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("MainWindow", "Select Room", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidget_2->horizontalHeaderItem(0);
        ___qtablewidgetitem1->setText(QApplication::translate("MainWindow", "Devices", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidget_2->verticalHeaderItem(0);
        ___qtablewidgetitem2->setText(QApplication::translate("MainWindow", "1", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidget_2->verticalHeaderItem(1);
        ___qtablewidgetitem3->setText(QApplication::translate("MainWindow", "2", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidget_2->verticalHeaderItem(2);
        ___qtablewidgetitem4->setText(QApplication::translate("MainWindow", "3", 0, QApplication::UnicodeUTF8));

        const bool __sortingEnabled = tableWidget_2->isSortingEnabled();
        tableWidget_2->setSortingEnabled(false);
        tableWidget_2->setSortingEnabled(__sortingEnabled);

        pushButton_7->setText(QApplication::translate("MainWindow", "Delete Selected Device", 0, QApplication::UnicodeUTF8));
        groupBox_4->setTitle(QApplication::translate("MainWindow", "Smart Decision Mode", 0, QApplication::UnicodeUTF8));
        checkBox_smartDM->setText(QString());
        label_8->setText(QApplication::translate("MainWindow", "Enabled", 0, QApplication::UnicodeUTF8));
        groupBox_5->setTitle(QApplication::translate("MainWindow", "Add New Room", 0, QApplication::UnicodeUTF8));
        textBox_newRoom->setPlaceholderText(QApplication::translate("MainWindow", "<Enter Room Name>", 0, QApplication::UnicodeUTF8));
        button_NewRoom->setText(QApplication::translate("MainWindow", "Add", 0, QApplication::UnicodeUTF8));
        groupBox_6->setTitle(QApplication::translate("MainWindow", "Delete Room", 0, QApplication::UnicodeUTF8));
        button_deleteRoom->setText(QApplication::translate("MainWindow", "Delete", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("MainWindow", "Set Date", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_setupconfig), QApplication::translate("MainWindow", "Setup and Configuration", 0, QApplication::UnicodeUTF8));
        groupBox_7->setTitle(QApplication::translate("MainWindow", "How to Use", 0, QApplication::UnicodeUTF8));
        dev1_id_5->setText(QApplication::translate("MainWindow", "-First make sure all Smart Switches and Load ", 0, QApplication::UnicodeUTF8));
        dev1_id_6->setText(QApplication::translate("MainWindow", "Controllers are plugged into the system.", 0, QApplication::UnicodeUTF8));
        dev1_id_7->setText(QApplication::translate("MainWindow", "-In Setup and Configuration, add all of the", 0, QApplication::UnicodeUTF8));
        dev1_id_14->setText(QApplication::translate("MainWindow", "rooms you wish to control.", 0, QApplication::UnicodeUTF8));
        dev1_id_15->setText(QApplication::translate("MainWindow", "-Use Device Detect to find all possible device", 0, QApplication::UnicodeUTF8));
        dev1_id_16->setText(QApplication::translate("MainWindow", "and add them to your desired rooms.", 0, QApplication::UnicodeUTF8));
        dev1_id_17->setText(QApplication::translate("MainWindow", "-Send Device Startup to launch the system", 0, QApplication::UnicodeUTF8));
        dev1_id_18->setText(QApplication::translate("MainWindow", "-In Room Manager, select any room to control", 0, QApplication::UnicodeUTF8));
        dev1_id_19->setText(QApplication::translate("MainWindow", "its devices and set thresholds", 0, QApplication::UnicodeUTF8));
        groupBox_8->setTitle(QApplication::translate("MainWindow", "Tips and Tricks", 0, QApplication::UnicodeUTF8));
        dev1_id_8->setText(QApplication::translate("MainWindow", "-For complete manual control of the system", 0, QApplication::UnicodeUTF8));
        dev1_id_9->setText(QApplication::translate("MainWindow", "and disable Smart Decision Mode.", 0, QApplication::UnicodeUTF8));
        dev1_id_10->setText(QApplication::translate("MainWindow", "-For energy efficiency create threshold settings", 0, QApplication::UnicodeUTF8));
        dev1_id_11->setText(QApplication::translate("MainWindow", "settings within certain ranges.", 0, QApplication::UnicodeUTF8));
        dev1_id_12->setText(QApplication::translate("MainWindow", "navigate to the Setup and Configuration page", 0, QApplication::UnicodeUTF8));
        dev1_id_13->setText(QApplication::translate("MainWindow", "to keep lighting, temperature, and humidity", 0, QApplication::UnicodeUTF8));
        checkBox->setText(QApplication::translate("MainWindow", "GPIO3_21", 0, QApplication::UnicodeUTF8));
        checkBox_3->setText(QApplication::translate("MainWindow", "GPIO1_15", 0, QApplication::UnicodeUTF8));
        checkBox_4->setText(QApplication::translate("MainWindow", "GPIO1_0", 0, QApplication::UnicodeUTF8));
        checkBox_2->setText(QApplication::translate("MainWindow", "GPIO1_13", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_help), QApplication::translate("MainWindow", "Help", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Ubuntu Condensed'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Ubuntu'; font-size:36pt; color:#000000;\">GARVIS</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">2015 G.A.R.V.I.S. Team 23</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        label_6->setText(QString());
        pushButton->setText(QApplication::translate("MainWindow", "Launch Keyboard", 0, QApplication::UnicodeUTF8));
        pushButton_2->setText(QApplication::translate("MainWindow", "Exit", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
